swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transaction/customers/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: User transactions of the month
      parameters:
        - name: id
          in: path
          required: true
          type: number
          description: id of the customer
      description: API for fetching a user transactions of this month
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/TransactionAll'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transaction/{id}:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: User Transaction
      parameters:
        - in: path
          name: id
          type: integer
          description: id of the transaction
          required: true
        - in: body
          name: data
          required: true
          description: id of the transaction
          schema:
            $ref: '#/definitions/DataTransaction'
      description: API for posting a user transaction
      responses:
        '200':
          description: User profile posted successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: User Transaction
      description: API for updating a user profile
      parameters:
        - in: path
          name: id
          type: integer
          description: get user transaction
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionGet'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: User Transaction
      description: API for updating a user transation
      parameters:
        - in: path
          name: id
          type: integer
          description: id of the transaction
          required: true
        - in: body
          name: dataUpdate
          description: Update user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/DataTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction updated successully
          schema:
            $ref: '#/definitions/TransactionPut'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: User Transaction
      description: API for deleting user transaction
      parameters:
        - in: path
          name: id
          type: integer
          description: delete one transaction
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction deleted successully
          schema:
            $ref: '#/definitions/TransactionDel'
        '204':
          description: The resource was deleted successfully.
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionAll:
    type: array
    items:
      type: object
      properties:
        date:
          type: string
          example: '03/01/2024'
        description: 
          type: string
          example: 'Golden Sun Bakery'
        amount:
          type: integer
          example: 26
  TransactionGet:
    type: array
    items:
      type: object
      properties:
        date:
          type: string
          example: '04/01/2024'
        description: 
          type: string
          example: 'Golden Sun Bakery'
        amount:
          type: integer
          example: 9.65
  TransactionPut:
    type: array
    items:
      type: object
      properties:
        date:
          type: string
          example: '06/01/2024'
        description: 
          type: string
          example: 'Golden Sun Bakery'
        amount:
          type: integer
          example: 128.26
  TransactionDel:
    type: array
    items:
      type: object
      properties:
        date:
          type: string
          example: '08/01/2024'
        description: 
          type: string
          example: 'Golden Sun Bakery'
        amount:
          type: integer
          example: 86.9
  DataTransaction:
    properties:
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: transaction note
    